### ISSUE TITLE
Can minSdk 9 work?

### ISSUE THREAD

**Issue by ThanosFisherman** [edubarr/header-decor#13]
Hello, I know this library has set minSdk to 15 but I tried this library on android 2.3. And It looks like the headers cover the entire screen. Check out the pic. 
I was wondering how hard can it be to support apis starting from 9 and above?
![device-2015-06-16-021708](https://cloud.githubusercontent.com/assets/4888330/8172839/e10f63c0-13cd-11e5-8b92-800a913cd1d1.png)

**Comment by edubarr** [comment]
The recyclerview is part of the v7 support library, so it shouldn't be too much work to support lower versions. I'll gladly accept a fix for this issue. :smile:

**Comment by robertoestivill** [comment]
Is there any reason why not to support api 14 ?
Would you take a PR for lowering the min sdk version to 14?

**Comment by edubarr** [comment]
I didn't care much for min SDK 14 due to the the current number of users on it. According to the [android dashboard](http://developer.android.com/about/dashboards/index.html), there's less than 0.1% of android users currently on API 14, which for all intents and purposes is nobody. There are more users on Froyo than on ICS, for example. In any case, if you want/need to support API 14 I'll gladly accept the PR.

**Comment by robertoestivill** [comment]
I understand your point.  
I have a different point of view when setting the minSdkVersion though.
Always start on the lowest sdk version and move up only if the API at that level does not provide the functionality you need (or is too much work to go around it). Under this line of thinking, lowering sdk version to 14 is (as far as i can tell) just a change of a number, since the library will work just fine as it doesn't require nothing api-15 specific. 
Also, while percentages are very small, 0.1% can be a huge number, specially when dealing with billions of installations.

**Comment by edubarr** [comment]
@robertoestivill sorry for taking so long to get back to you. I'm fine with changing the minSDK to 14, you can create a pull request for it if you want, if not I'll change it next time I update the library. :+1:

**Comment by robertoestivill** [comment]
@edubarr created a PR for lowering the library min sdk to api level 14.
https://github.com/edubarr/header-decor/pull/19
Thanks

**Comment by edubarr** [comment]
I'll be closing this issue since there no one has come forward willing to support minSDK 9. For my use case, the current minSDK works just fine. If anyone wishes to support a lower SDK I will gladly accept pull requests.
