### ISSUE TITLE
Switched paramterets in getHeaderTop

### ISSUE THREAD

**Issue by lhoracek** [edubarr/header-decor#23]
You have switched parameters in getHeaderTop method in DoubleHeaderDecoration. Calling it with subHeader, header as params, but method expects exactly opposit order (header, subHeader) looks like it works by mistake :-)

**Comment by edubarr** [comment]
@lhoracek thanks for pointing that out! It's been a while since I touched that code, but I'll have a look and sort out any issues. :+1:

**Comment by edubarr** [comment]
@lhoracek I just realized I never got back to you on this. It was a mistake to switch header and subheaders there! The code only works because all it cares about is the x coordinate and height of both the header and subheader (we're trying to find where it should go) so the order of the things doesn't really matter. I've fixed it along with a few other changes that I'm currently working on. Thanks once again! :)
