### ISSUE TITLE
Sticky Header and View overlay

### ISSUE THREAD

**Issue by ProfessorMLM** [edubarr/header-decor#30]
In Sticky Header both onCreateHeaderViewHolder and onCreateViewHolder is invoked in one item in same time

**Comment by edubarr** [comment]
I'm not sure I understand your issue, but `onCreateHeaderViewHolder` is called whenever you first encounter a view that needs a header. Since there's no recycling of view for the headers, each entry in the list with a header has its own header view. This may occur in the same pass as `onCreateViewHolder` is called which is the intended behaviour.

Please clarify your issue/question if this answer doesn't help you. Thanks. :)

**Comment by ProfessorMLM** [comment]
My question is about two method onCreateViewHoder and onCreateHeaderViewHolder:
1- When onCreateViewHolder is called, must not called onCreateHeaderViewHolder 
2- When onCreateHeaderViewHolder is called, must not called oncreateViewHolder
can be called two method and place two view in one position for example position 10
and My main Issue is that for place 0 ,10, 20, 30 i want just onCreateHeaderViewHolder is called
and other positions onCreateViewHolder is called and put view in that position

**Comment by ProfessorMLM** [comment]
These codes are different
decor = new StickyHeaderDecoration(adapter);                 //Sticky header
decor = new StickyHeaderDecoration(adapter, true);         //Inline Sticky header
My Problem solved
