### ISSUE TITLE
Header-decor with Expandable RecyclerView

### ISSUE THREAD

**Issue by boyfox** [edubarr/header-decor#31]
Hi Eduardo! I tried use Header-decor view with Expandable RecyclerView library (by Ryan Brooks https://github.com/rbro112/expandable-recycler-view ) to create Expandable items with sticky headers but, I have a problem, can you write any commentary to me. When I StickerheaderDecoration send request to adapter by method getHeaderId I can retrun right header position but when expandable items expended then header will be draw header on incorrect position. Can you any suggestion to solve this?

**Comment by edubarr** [comment]
I haven't really used the header library with expandable items. The cause might be the change of item numbers in the list after an item is expanded since it seems like the library you're using adds extra items to the adapter, so calling `clearHeaderCache` on the decoration might force the headers to be drawn in the correct place. If you could create a sample project that shows this behaviour I could look more into it on my free time. Thanks!

**Comment by davideas** [comment]
@boyfox if you search both functionalities, you might want to check my implementation on my page. Feel free to ask there.

**Comment by boyfox** [comment]
Thanks @davideas, I seen your project "FlexibleAdapter", I will be try it today.
