### ISSUE TITLE
Can sticky headers contains one or more clickable button?

### ISSUE THREAD

**Issue by wangkunhui** [edubarr/header-decor#72]

**Comment by hanscappelle** [comment]
Check this issue https://github.com/edubarr/header-decor/issues/38 for some more information on how to implement click events on headers. Check that ticket for more details since there is some code required, it all starts with:

`decoration = new StickyHeaderDecoration(adapter);
recyclerView.addOnItemTouchListener(new StickyHeadersTouchListener(recyclerView, decoration))`
